(DEFUN C:Zenklai()
  (setq taskas (getpoint "\nIveskite bazinio tasko pradine koordinate:"))
    (COMMAND "CHPROP" sel "" "COLOR" "BYLAYER" "LWEIGHT" "0.30" "LTYPE" "BYLAYER" "")
  (setq galva (list (+ (car taskas) 0) (+ (cadr taskas) 0)))
  (setq galva2 (list (+ (car taskas) 0) (+ (cadr taskas) 15)))
  (setq torso1 (list (+ (car galva) 0) (- (cadr galva) 15)))
  (setq torso2 (list (+ (car taskas) 0) (- (cadr taskas) 55)))
  (setq Dkoja1 (list (- (car torso2) 7) (+ (cadr torso2) 0)))
  (setq Dkoja2 (list (+ (car Dkoja1) 0) (- (cadr Dkoja1) 40)))
  (setq Kkoja1 (list (+ (car torso2) 7) (+ (cadr torso2) 0)))
  (setq Kkoja2 (list (+ (car Kkoja1) 0) (- (cadr Kkoja1) 40)))
  (setq Dpetys1 (list (- (car torso1) 12) (- (cadr torso1) 3)))
  (setq Dpetys2 (list (- (car Dpetys1) 15) (+ (cadr Dpetys1) 0)))
  (setq Kpetys1 (list (+ (car torso1) 12) (- (cadr torso1) 3)))
  (setq Kpetys2 (list (+ (car Kpetys1) 15) (+ (cadr Kpetys1) 0)))
  ;(setq Dranka1 (list (+ (car taskas) 50) (+ (cadr taskas) 0)))
  ;(setq Dranka2 (list (+ (car taskas) 50) (+ (cadr taskas) 0)))
  ;(setq Kranka1 (list (+ (car taskas) 50) (+ (cadr taskas) 0)))
  ;(setq Kranka2 (list (+ (car taskas) 50) (+ (cadr taskas) 0)))
  (command "circle" galva 15 -enter)
  (command "pline" torso1 "w" 25 20 torso2 -enter)
  (command "hatch" "solid" galva galva2 -enter)
  (command "pline" Kkoja1 "w" 6 5 Kkoja2 -enter)
  (command "pline" Dkoja1 "w" 6 5 Dkoja2 -enter)
  (command "pline" Dpetys1 "w" 5 6 Dpetys2 -enter)
  (command "pline" Kpetys1 "w" 5 6 Kpetys2 -enter)
)